#!/usr/bin/env bash
# install.sh — Catylst CLI installer
#
# Sets up the `catylst` command globally so you can generate KMP projects
# from anywhere with an interactive wizard.
#
# One-liner install:
#   bash <(curl -sSL https://raw.githubusercontent.com/rohit-554/Catylst/main/scripts/install.sh)
#
# After install:
#   catylst --interactive

set -e

REPO_URL="https://github.com/rohit-554/Catylst.git"
JAR_URL="https://github.com/rohit-554/Catylst/releases/latest/download/catylst-cli.jar"
TEMPLATE_DIR="${CATYLST_TEMPLATE_DIR:-$HOME/.catylst/template}"
BIN_DIR="${CATYLST_BIN_DIR:-$HOME/.local/bin}"
JAR_PATH="$HOME/.catylst/catylst-cli.jar"

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
DIM="\033[2m"
RESET="\033[0m"

# ── dependency check ──────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}  Catylst KMP Project Generator${RESET}"
echo -e "${DIM}  ────────────────────────────────────────${RESET}"
echo ""

for cmd in git curl java; do
    if ! command -v "$cmd" &>/dev/null; then
        echo -e "  ${YELLOW}✗  '$cmd' is required but not found.${RESET}"
        [[ "$cmd" == "java" ]] && echo "     Install JDK 17+: https://adoptium.net"
        exit 1
    fi
done

JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
if [[ "$JAVA_VERSION" -lt 17 ]] 2>/dev/null; then
    echo -e "  ${YELLOW}✗  JDK 17+ required (found $JAVA_VERSION). Install from https://adoptium.net${RESET}"
    exit 1
fi

echo -e "  ${GREEN}✓${RESET}  Java $JAVA_VERSION"

# ── template ──────────────────────────────────────────────────────────────────

mkdir -p "$HOME/.catylst"

if [[ -d "$TEMPLATE_DIR/.git" ]]; then
    echo -e "  ${CYAN}↻${RESET}  Updating template..."
    git -C "$TEMPLATE_DIR" pull --quiet --rebase 2>/dev/null \
        || echo -e "  ${YELLOW}⚠  Could not update template (offline?). Using existing.${RESET}"
else
    echo -e "  ${CYAN}↓${RESET}  Cloning template to ~/.catylst/template ..."
    rm -rf "$TEMPLATE_DIR"
    git clone --depth 1 --quiet "$REPO_URL" "$TEMPLATE_DIR"
fi

echo -e "  ${GREEN}✓${RESET}  Template ready"

# ── JAR ───────────────────────────────────────────────────────────────────────

if [[ -f "$TEMPLATE_DIR/cli-generator/build/libs/cli-generator-1.0.0.jar" ]]; then
    # Dev mode — use local build
    cp "$TEMPLATE_DIR/cli-generator/build/libs/cli-generator-1.0.0.jar" "$JAR_PATH"
    echo -e "  ${GREEN}✓${RESET}  Using local build"
else
    echo -e "  ${CYAN}↓${RESET}  Downloading catylst-cli.jar ..."
    curl -sSL -o "$JAR_PATH" "$JAR_URL" || {
        echo -e "  ${YELLOW}✗  Download failed. Build locally:${RESET}"
        echo "     cd ~/.catylst/template/cli-generator && ./gradlew jar"
        exit 1
    }
    echo -e "  ${GREEN}✓${RESET}  CLI downloaded"
fi

# ── wrapper script ────────────────────────────────────────────────────────────

mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/catylst" << EOF
#!/usr/bin/env bash
# Catylst CLI wrapper — generated by install.sh
# Template: $TEMPLATE_DIR
# JAR:      $JAR_PATH

cd "$TEMPLATE_DIR/cli-generator" && \\
  java -jar "$JAR_PATH" "\$@"
EOF

chmod +x "$BIN_DIR/catylst"
echo -e "  ${GREEN}✓${RESET}  Installed to $BIN_DIR/catylst"

# ── PATH hint ─────────────────────────────────────────────────────────────────

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo -e "  ${YELLOW}⚠  $BIN_DIR is not in your PATH.${RESET}"
    echo "     Add this to your shell profile (~/.zshrc or ~/.bashrc):"
    echo ""
    echo -e "     ${CYAN}export PATH=\"$BIN_DIR:\$PATH\"${RESET}"
    echo ""
    echo "     Then restart your terminal or run:"
    echo -e "     ${CYAN}source ~/.zshrc${RESET}"
fi

# ── done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${DIM}  ────────────────────────────────────────${RESET}"
echo -e "  ${GREEN}${BOLD}All done!${RESET} Start your project:"
echo ""
echo -e "  ${CYAN}catylst --interactive${RESET}"
echo ""
echo -e "  ${DIM}Or non-interactive:${RESET}"
echo -e "  ${DIM}catylst --package com.example.app --name MyApp${RESET}"
echo ""
