package com.catylst.plugin.template

import com.catylst.plugin.model.AiProvider
import com.catylst.plugin.model.GeneratorConfig
import java.io.File

object ProjectCleaner {

    // Wizard skill ID → .claude/skills folder name (they don't all match 1:1).
    private val SKILL_FOLDERS = mapOf(
        "bloom-build" to "bloom-build",
        "bloom-navigate" to "bloom-navigate",
        "compose-expert" to "compose",
        "clean-code" to "clean-code",
        "figma-to-compose" to "figma-mcp"
    )

    fun clean(projectDir: File, config: GeneratorConfig) {
        applyAgentSkills(projectDir, config)
        File(projectDir, "npm").deleteRecursively()
        File(projectDir, "cli-generator").deleteRecursively()
        File(projectDir, "catylst-plugin").deleteRecursively()
        File(projectDir, "docs").deleteRecursively()
        // local.properties holds a machine-specific sdk.dir path; Android Studio regenerates it on import
        File(projectDir, "local.properties").delete()
        File(projectDir, "scripts/setup.sh").delete()
        File(projectDir, "scripts/install.sh").delete()
        File(projectDir, "AGENTS.md").delete()
        File(projectDir, "Plugin.md").delete()
        File(projectDir, "GENERATOR_PLAN.md").delete()

        // Strip any internal module includes that don't belong in the generated project
        stripInternalIncludes(projectDir)

        generateReadme(projectDir, config)

        File(projectDir, ".git").deleteRecursively()
    }

    /**
     * Handles the `.claude` agent tooling folder. When "agent-skills" is selected, keep `.claude`
     * but prune `skills/` down to the user's chosen skills. Otherwise remove `.claude` entirely.
     */
    private fun applyAgentSkills(projectDir: File, config: GeneratorConfig) {
        val claudeDir = File(projectDir, ".claude")
        if (!claudeDir.exists()) return

        if ("agent-skills" !in config.features) {
            claudeDir.deleteRecursively()
            return
        }

        val keep = config.selectedSkillIds.mapNotNull { SKILL_FOLDERS[it] }.toSet()
        if (keep.isEmpty()) {
            // Feature on but nothing chosen — no skills to ship.
            claudeDir.deleteRecursively()
            return
        }

        File(claudeDir, "skills").listFiles()?.forEach { dir ->
            if (dir.isDirectory && dir.name !in keep) dir.deleteRecursively()
        }
    }

    private fun stripInternalIncludes(projectDir: File) {
        val settingsFile = File(projectDir, "settings.gradle.kts")
        if (!settingsFile.exists()) return
        val internalModules = setOf(":catylst-plugin", ":cli-generator")
        val lines = settingsFile.readLines()
        val cleaned = lines.filter { line ->
            internalModules.none { line.contains("include(\"$it\")") }
        }
        if (cleaned.size != lines.size) {
            settingsFile.writeText(cleaned.joinToString("\n"))
        }
    }

    private fun generateReadme(projectDir: File, config: GeneratorConfig) {
        val readme = File(projectDir, "README.md")
        val featuresList = config.features.joinToString("\n") { "- $it" }
        val aiProviderText = if (config.aiProvider != AiProvider.NONE) {
            "\n- AI Provider: ${config.aiProvider.name.lowercase().replaceFirstChar { it.uppercase() }}"
        } else ""

        val content = """# ${config.appName}

Generated with [Catylst KMP Starter Kit](https://github.com/Rohit-554/Catylst).

## Features
$featuresList$aiProviderText
- Sample Code: ${if (config.sampleCode) "Included" else "Excluded"}

## Platforms
- Android: ${if (config.includeAndroid) "✅" else "❌"}
- iOS: ${if (config.includeIos) "✅" else "❌"}
- Desktop: ${if (config.includeDesktop) "✅" else "❌"}

## Getting Started

1. Open the project in Android Studio or IntelliJ IDEA
2. Sync Gradle
3. Run `./gradlew :androidApp:assembleDebug` to build the Android app

## Package
`${config.packageName}`

---
Generated by Catylst Plugin
""".trimIndent()

        readme.writeText(content)
    }
}
