package com.catylst.cli.template

import com.catylst.cli.model.GeneratorConfig
import java.io.File

object ProjectCleaner {

    fun clean(projectDir: File, config: GeneratorConfig) {
        println("🧹 Cleaning up project...")

        // Remove .claude/ directory
        File(projectDir, ".claude").deleteRecursively()

        // Remove docs/ folder
        File(projectDir, "docs").deleteRecursively()

        // Remove scripts/setup.sh, scripts/install.sh
        File(projectDir, "scripts/setup.sh").delete()
        File(projectDir, "scripts/install.sh").delete()

        // Remove AGENTS.md, Plugin.md, GENERATOR_PLAN.md
        File(projectDir, "AGENTS.md").delete()
        File(projectDir, "Plugin.md").delete()
        File(projectDir, "GENERATOR_PLAN.md").delete()

        // Replace README.md with generated one
        generateReadme(projectDir, config)

        // Delete .git/ directory for fresh start
        File(projectDir, ".git").deleteRecursively()

        println("✅ Cleanup complete")
    }

    private fun generateReadme(projectDir: File, config: GeneratorConfig) {
        val readme = File(projectDir, "README.md")
        val featuresList = config.features.joinToString("\n") { "- $it" }
        val aiProviderText = if (config.aiProvider != com.catylst.cli.model.AiProvider.NONE) {
            "\n- AI Provider: ${config.aiProvider.name.lowercase().replaceFirstChar { it.uppercase() }}"
        } else ""

        val content = """# ${config.appName}

Generated with Catylst KMP Starter Kit.

## Features
$featuresList$aiProviderText
- Sample Code: ${if (config.sampleCode) "Included" else "Excluded"}

## Platforms
- Android: ${if (config.includeAndroid) "✅" else "❌"}
- iOS: ${if (config.includeIos) "✅" else "❌"}
- Desktop: ${if (config.includeDesktop) "✅" else "❌"}

## Getting Started

1. Open the project in Android Studio or IntelliJ IDEA
2. Sync Gradle
3. Run `./gradlew :androidApp:assembleDebug` to build the Android app

## Package
`${config.packageName}`

---
Generated by Catylst CLI
""".trimIndent()

        readme.writeText(content)
    }
}
